import { copyFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, type Plugin } from "vite";
import react, { reactCompilerPreset } from '@vitejs/plugin-react'
import babel from '@rolldown/plugin-babel'

const coreCryptoWasmSource = fileURLToPath(
  new URL(
    "./node_modules/@wireapp/core-crypto/src/autogenerated/core-crypto-ffi_bg.wasm",
    import.meta.url,
  ),
);
const coreCryptoWasmTarget = fileURLToPath(
  new URL("./public/core-crypto-ffi_bg.wasm", import.meta.url),
);

function syncCoreCryptoWasm() {
  mkdirSync(dirname(coreCryptoWasmTarget), { recursive: true });
  copyFileSync(coreCryptoWasmSource, coreCryptoWasmTarget);
}

function coreCryptoWasmPlugin(): Plugin {
  return {
    name: "core-crypto-wasm-sync",
    buildStart() {
      syncCoreCryptoWasm();
    },
    configureServer() {
      syncCoreCryptoWasm();
    },
  };
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    coreCryptoWasmPlugin(),
    react(),
    babel({ presets: [reactCompilerPreset()] })
  ],
})
